---
include:
  - project: "misc/gitlab_templates"
    ref: master
    file: "/molecule/.base-template.yml"
  - project: "misc/gitlab_templates"
    ref: master
    file: "/.clone-before-script-template.yml"

stages:
  - ansible_2_8_x

ansible_2_8_x:
  stage: ansible_2_8_x
  extends: .molecule.default
  image: zerodowntime/gitlab_runner_executor_molecule:ansible-2.8
  script:
    - molecule test -s libvirt
