---
include:
  - project: 'misc/gitlab_templates'
    ref: master
    file: '/molecule/.base-template.yml'
  - project: 'misc/gitlab_templates'
    ref: master
    file: '/.clone-before-script-template.yml'

stages:
  - ansible2_7_8

ansible2_7_8:
  stage: ansible2_7_8
  extends: .molecule.default
  image: zerodowntime/gitlab_runner_executor_molecule:ansible-2.7.8
  script:
    - molecule test -s libvirt
