---
# roles/zerodowntime.docker/tasks/swarm.yml

- name: Docker swarm init
  become: true
  docker_swarm:
    state: present
    advertise_addr: "{{ docker__swarm_advertise_addr|default(omit,true) }}"
  when:
    - docker__swarm_init|bool

# Not debug. Needed for get registered vars
- name: Get docker swarm status
  become: true
  docker_swarm:
    state: inspect
  register: docker___swarm_info

- name: Join node to docker swarm
  become: true
  docker_swarm:
    state: join
    advertise_addr: "{{ docker__swarm_advertise_addr }}"
    join_token: "{{ docker__swarm_join_token }}"
    remote_addrs: "{{ docker__swarm_join_addr }}"


- name: Set docker node availability
  become: true
  command: "docker node update --availability {{ docker__availability }} {{ docker__swarm_node_name }}"
  when:
    - docker__availability is defined and docker__availability
