---
# zerodowntime.docker/handlers/main.yml

- name: restart docker
  become: true
  systemd:
    name: "{{ docker__service_name }}"
    state: restarted


- name: start docker
  become: true
  systemd:
    name: "{{ docker__service_name }}"
    state: started


- name: stop docker
  become: true
  systemd:
    name: "{{ docker__service_name }}"
    state: stopped
